### PR TITLE
also test on 1.3

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This can get expensive. What's the context on this?

**Comment by KristofferC** [comment]
It failed on PkgEval for 1.3 so want to see if it is the same here.

**Comment by KristofferC** [comment]
https://gist.github.com/KristofferC/47577ec5ad3b4418fd98f20bc3d91957#file-stochasticdiffeq-log

Seems to be something in DynamicPolynomials.

**Comment by ChrisRackauckas** [comment]
>Might make sense to bump that to 1.2?

Yeah, that would make sense.

**Comment by KristofferC** [comment]
Here is a PR that fixes this for another package https://github.com/wormell/Poltergeist.jl/pull/8. Perhaps the same could be applied to DynamicPolynomials.

**Comment by KristofferC** [comment]
From that log: ` Installed DynamicPolynomials ────── v0.1.4`. This is a very old version of DynamicPolynomials. Wonder why that gets installed.

**Comment by KristofferC** [comment]
https://github.com/JuliaHomotopyContinuation/HomotopyContinuation.jl/pull/313 maybe...

**Comment by devmotion** [comment]
Actually we had a similar (the same?) issue before in DiffEqBase: https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/322#issuecomment-521553904 Since HomotopyContinuation did not support Parameters 0.11.0, we ended up with this very old version of DynamicPolynomials. The issue was solved by updating HomotopyContinuation's compatibility with Parameters IIRC

**Comment by KristofferC** [comment]
Ok, so there is some old version that doesn't declare any compat with Parameters at all that the resolver finds. That's one of the "dangers" when starting to add upper bounds but there are old versions with no upper bounds. Anyway, https://github.com/JuliaHomotopyContinuation/HomotopyContinuation.jl/pull/313 should fix it then.

**Pull request merged**
