### PR TITLE
Implemented SROCK method for Stratonovich form

### PR DESCRIPTION
**Pull request by deeepeshthakur**
@ChrisRackauckas 
Implemented SROCK method from [S-ROCK: Chebyshev Methods for Stiff Stochastic Differential](https://doi.org/10.1137/070679375)
I might have not included all the tests.
[Weaved test results](https://htmlpreview.github.io/?https://github.com/deeepeshthakur/Urls/blob/master/SROCK1_convergence_test.html)

Though there are two things that need to be finalised.
1.  Spectral Radius is assumed to be twice of that calculated by `integrator.f` only.
2.  Constant factor of the stability domain is taken to be the minimum. 

#73

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
wrong link for the Weave

**Comment by deeepeshthakur** [comment]
I forgot to add the link.Adding it. Sorry

**Comment by deeepeshthakur** [comment]
> wrong link for the Weave

Done!

**Comment by ChrisRackauckas** [comment]
It is shown in [3] that the S-ROCK methods applied to (3.30)
have order 1/2 in the strong sense and order 1 in the weak sense. However, if the
diffusion terms satisfy a commutativity condition
then the S-ROCK methods have strong order 1

We should make sure to document the order condition exactly like that.

**Comment by ChrisRackauckas** [comment]
Convergence plots look good

**Comment by ChrisRackauckas** [comment]
I didn't realize SROCK was Stratanovich convergent. 

https://math.stackexchange.com/questions/2296945/conversion-between-solution-to-stratonovich-sde-and-it%C3%B4-sde

A followup PR could do that ggprime RK calculation approximation to make a Ito version of it.

**Comment by ChrisRackauckas** [comment]
>Spectral Radius is assumed to be twice of that calculated by integrator.f only.

What do you mean? Is this in the paper?

**Comment by deeepeshthakur** [comment]
You know. I realised it today.For the last two days I'm testing this on Ito's form problems

**Comment by deeepeshthakur** [comment]
> > Spectral Radius is assumed to be twice of that calculated by integrator.f only.
> 
> What do you mean? Is this in the paper?

Actually no. In the paper the have said to take the least number of stages such that the stability domain is greater than spectral radius

**Comment by ChrisRackauckas** [comment]
https://projecteuclid.org/download/pdf_1/euclid.cms/1229619673 is the Ito one. I think we should have that be a choice that defaults to Ito, but do that in a followup PR.

**Comment by deeepeshthakur** [comment]
image
This is for the second point

**Comment by deeepeshthakur** [comment]
Current implementation is conservative. And assumes the smallest stabilty domain.

**Comment by deeepeshthakur** [comment]
> https://projecteuclid.org/download/pdf_1/euclid.cms/1229619673 is the Ito one. I think we should have that be a choice that defaults to Ito, but do that in a followup PR.

This paper is `SROCK4`. I mean fourth in order of implementation.

**Comment by ChrisRackauckas** [comment]
>This paper is SROCK4. I mean fourth in order of implementation.

I think down the line we want `SROCK(interpretation=:Stratonovich)` and `SROCK(interpretation=:Ito)`, matching the other methods, defaulting to Ito, using that paper. For now let's skip it though. Open an issue on that.

**Comment by deeepeshthakur** [comment]
@ChrisRackauckas 
Travis?

**Pull request merged**
