### PR TITLE
Changes for NLSolver change

### PR DESCRIPTION
**Pull request by kanav99**
Ref: JuliaDiffEq/DiffEqBase.jl#250

Let the tests pass first. I have some doubt too - Do SKenCarp need two copies of `linsolve` or `dz` or `jac_config`? Currently we are making two copies of these variables.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
It shouldn't need two copies.

**Comment by kanav99** [comment]
The `pr` test timed out but `push` passed. We need to split the tests even more. Should we merge this?

**Comment by devmotion** [comment]
Maybe getting rid of the deprecations in DiffEqDevTools could speed up things a bit. But probably it should be adjusted at least for Appveyor.

**Comment by ChrisRackauckas** [comment]
yeah devtools needs a tag I think.

**Pull request merged**
