### PR TITLE
SKSROCK

### PR DESCRIPTION
**Pull request by deeepeshthakur**
@ChrisRackauckas 
Implements `SKROCK` from [Optimal Explicit Stabilized Integrator of Weak Order One for Stiff and Ergodic Stochastic Differential Equations](https://arxiv.org/abs/1708.08145)
**Current version is without post_processing**
#73 
Also I not sure whether to make PSKROCK (the one with post processing) a new method or add as an option.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Make it an option.

**Comment by deeepeshthakur** [comment]
I'll make ithis WIP till I finish that

**Comment by deeepeshthakur** [comment]
@ChrisRackauckas I'm not completely sure about the post processing.
It's supposed to give weak order 2, I'm getting 1

**Comment by ChrisRackauckas** [comment]
Open an issue on it, and keep continuing. I can take a look maybe tomorrow or Thursday.

**Comment by deeepeshthakur** [comment]
#176

**Pull request merged**
