### PR TITLE
Remove redundant NLSolve Fields

### PR DESCRIPTION
**Pull request by kanav99**
Needs some code deleting as some of the functions are not used at all.

### CODE REVIEW

**Comment by kanav99** [comment]
Just to report, SDIRK don't work with NLSolve other than NLNewton, even on master.

**Comment by kanav99** [comment]
Oops is this a mistake?

**Comment by ChrisRackauckas** [comment]
? I don't know

**Comment by kanav99** [comment]
It is ready to be merged, but its rebased on #204 , I want it to be approved before merge @ChrisRackauckas @deeepeshthakur

**Pull request merged**
